/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as FAQsRouteImport } from './routes/FAQs'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as MoviesSlugRouteImport } from './routes/movies.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicSeedAdminRouteImport } from './routes/api/public/seed-admin'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const FAQsRoute = FAQsRouteImport.update({
  id: '/FAQs',
  path: '/FAQs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesSlugRoute = MoviesSlugRouteImport.update({
  id: '/movies/$slug',
  path: '/movies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSeedAdminRoute = ApiPublicSeedAdminRouteImport.update({
  id: '/api/public/seed-admin',
  path: '/api/public/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/FAQs': typeof FAQsRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/live': typeof LiveRoute
  '/my-list': typeof MyListRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/series': typeof SeriesRoute
  '/shorts': typeof ShortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/movies/': typeof MoviesIndexRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/FAQs': typeof FAQsRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/live': typeof LiveRoute
  '/my-list': typeof MyListRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/series': typeof SeriesRoute
  '/shorts': typeof ShortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/movies': typeof MoviesIndexRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/FAQs': typeof FAQsRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/live': typeof LiveRoute
  '/my-list': typeof MyListRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/series': typeof SeriesRoute
  '/shorts': typeof ShortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/movies/': typeof MoviesIndexRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/FAQs'
    | '/admin-login'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/live'
    | '/my-list'
    | '/pricing'
    | '/privacy'
    | '/series'
    | '/shorts'
    | '/sitemap.xml'
    | '/terms'
    | '/trending'
    | '/admin'
    | '/dashboard'
    | '/movies/$slug'
    | '/watch/$slug'
    | '/movies/'
    | '/api/public/seed-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/FAQs'
    | '/admin-login'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/live'
    | '/my-list'
    | '/pricing'
    | '/privacy'
    | '/series'
    | '/shorts'
    | '/sitemap.xml'
    | '/terms'
    | '/trending'
    | '/admin'
    | '/dashboard'
    | '/movies/$slug'
    | '/watch/$slug'
    | '/movies'
    | '/api/public/seed-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/FAQs'
    | '/admin-login'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/live'
    | '/my-list'
    | '/pricing'
    | '/privacy'
    | '/series'
    | '/shorts'
    | '/sitemap.xml'
    | '/terms'
    | '/trending'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/movies/$slug'
    | '/watch/$slug'
    | '/movies/'
    | '/api/public/seed-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  FAQsRoute: typeof FAQsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  LiveRoute: typeof LiveRoute
  MyListRoute: typeof MyListRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SeriesRoute: typeof SeriesRoute
  ShortsRoute: typeof ShortsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrendingRoute: typeof TrendingRoute
  MoviesSlugRoute: typeof MoviesSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  ApiPublicSeedAdminRoute: typeof ApiPublicSeedAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FAQs': {
      id: '/FAQs'
      path: '/FAQs'
      fullPath: '/FAQs'
      preLoaderRoute: typeof FAQsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$slug': {
      id: '/movies/$slug'
      path: '/movies/$slug'
      fullPath: '/movies/$slug'
      preLoaderRoute: typeof MoviesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/seed-admin': {
      id: '/api/public/seed-admin'
      path: '/api/public/seed-admin'
      fullPath: '/api/public/seed-admin'
      preLoaderRoute: typeof ApiPublicSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  FAQsRoute: FAQsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  LiveRoute: LiveRoute,
  MyListRoute: MyListRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SeriesRoute: SeriesRoute,
  ShortsRoute: ShortsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrendingRoute: TrendingRoute,
  MoviesSlugRoute: MoviesSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  ApiPublicSeedAdminRoute: ApiPublicSeedAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
